sensor:
  - platform: template
    sensors:
      water_tank_level:
        friendly_name: "Water Tank Level"
        value_template: >
          {% if is_state('binary_sensor.water_tank_d1_mini_water_level_5', 'on') %}
            100
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_4', 'on') %}
            80
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_3', 'on') %}
            60
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_2', 'on') %}
            30
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_1', 'on') %}
            15
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "%"
