esphome:
  name: water-tank-d1-mini
  friendly_name: Water-Tank_D1_mini

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret water_tank_d1_mini_key

ota:
  password: !secret water_tank_d1_mini_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Tank-D1-Mini"
    password: "haha2205"

captive_portal:

# Using the delayed on off filter to get rid of random state changes 
# that could happen because of the water splashing around
binary_sensor:
  - platform: gpio
    pin:
      number: 3
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Water Level 1"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms

    
  - platform: gpio
    pin:
      number: 12
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Water Level 2"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms
    
  - platform: gpio
    pin:
      number: 13
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Water Level 3"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms

  - platform: gpio
    pin:
      number: 14
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Water Level 4"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms
  
  - platform: gpio
    pin: 
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    name: "Motor switch"
    filters: 
      - delayed_on_off: 500ms

  - platform: gpio
    pin: 
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    name: "RO switch"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 500ms


dallas:
  - pin: GPIO16

sensor:
  - platform: dallas
    address: 0xaa0000006a2fc128
    name: "DS18B20 Temperature"

switch:
  - platform: gpio
    pin: GPIO4
    name: "Water Pump Relay"
    id: motor_relay
    restore_mode: ALWAYS_OFF
    inverted: True

  - platform: gpio
    pin: GPIO5
    name: "RO Filter Relay"
    id: ro_relay
    restore_mode: ALWAYS_OFF
    inverted: True

