esphome:
  name: water-tank-d1-mini
  friendly_name: Water-Tank_D1_mini

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret water_tank_d1_mini_key

ota:
  password: !secret water_tank_d1_mini_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Tank-D1-Mini"
    password: "haha2205"

captive_portal:


binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "Water Level 1"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms
    on_state:
      then:
        - switch.turn_on: motor_relay

    
  - platform: gpio
    pin: 
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Water Level 2"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms
    
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Water Level 3"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms

  - platform: gpio
    pin: 
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "Water Level 4"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms

  - platform: gpio
    pin: 
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    name: "Water Level 5"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 3000ms
    on_state:
      then:
        - switch.turn_off: motor_relay
  
  - platform: gpio
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Motor switch"
    filters: 
      - delayed_on_off: 1000ms

  - platform: gpio
    pin: 
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "RO switch"
    device_class: "moisture"
    filters: 
      - delayed_on_off: 1000ms


dallas:
  - pin: GPIO2

sensor:
  - platform: dallas
    address: 0xaa0000006a2fc128
    name: "DS18B20 Temperature"

switch:
  - platform: gpio
    pin: GPIO4
    name: "Water Pump Relay"
    id: motor_relay
    restore_mode: ALWAYS_OFF
    inverted: True

  - platform: gpio
    pin: GPIO5
    name: "RO Filter Relay"
    id: ro_relay
    restore_mode: ALWAYS_OFF
    inverted: True

